/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InvitationsRouteImport } from './routes/invitations'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as UsernameRequestsRouteImport } from './routes/username-requests'
import { Route as FilesIndexRouteImport } from './routes/files/index'
import { Route as SettingsSharingRouteImport } from './routes/settings/sharing'
import { Route as StorageIndexRouteImport } from './routes/storage/index'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as UsersUserIdRouteImport } from './routes/users/$userId'
import { Route as UsersNewRouteImport } from './routes/users/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationsRoute = InvitationsRouteImport.update({
  id: '/invitations',
  path: '/invitations',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const UsernameRequestsRoute = UsernameRequestsRouteImport.update({
  id: '/username-requests',
  path: '/username-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesIndexRoute = FilesIndexRouteImport.update({
  id: '/files/',
  path: '/files/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSharingRoute = SettingsSharingRouteImport.update({
  id: '/settings/sharing',
  path: '/settings/sharing',
  getParentRoute: () => rootRouteImport,
} as any)
const StorageIndexRoute = StorageIndexRouteImport.update({
  id: '/storage/',
  path: '/storage/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUserIdRoute = UsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersNewRoute = UsersNewRouteImport.update({
  id: '/users/new',
  path: '/users/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/invitations': typeof InvitationsRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/username-requests': typeof UsernameRequestsRoute
  '/settings/sharing': typeof SettingsSharingRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/users/new': typeof UsersNewRoute
  '/files/': typeof FilesIndexRoute
  '/storage/': typeof StorageIndexRoute
  '/users/': typeof UsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/invitations': typeof InvitationsRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/username-requests': typeof UsernameRequestsRoute
  '/settings/sharing': typeof SettingsSharingRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/users/new': typeof UsersNewRoute
  '/files': typeof FilesIndexRoute
  '/storage': typeof StorageIndexRoute
  '/users': typeof UsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/invitations': typeof InvitationsRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/username-requests': typeof UsernameRequestsRoute
  '/settings/sharing': typeof SettingsSharingRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/users/new': typeof UsersNewRoute
  '/files/': typeof FilesIndexRoute
  '/storage/': typeof StorageIndexRoute
  '/users/': typeof UsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/invitations'
    | '/login'
    | '/setup'
    | '/username-requests'
    | '/settings/sharing'
    | '/users/$userId'
    | '/users/new'
    | '/files/'
    | '/storage/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/invitations'
    | '/login'
    | '/setup'
    | '/username-requests'
    | '/settings/sharing'
    | '/users/$userId'
    | '/users/new'
    | '/files'
    | '/storage'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/invitations'
    | '/login'
    | '/setup'
    | '/username-requests'
    | '/settings/sharing'
    | '/users/$userId'
    | '/users/new'
    | '/files/'
    | '/storage/'
    | '/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InvitationsRoute: typeof InvitationsRoute
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
  UsernameRequestsRoute: typeof UsernameRequestsRoute
  SettingsSharingRoute: typeof SettingsSharingRoute
  UsersUserIdRoute: typeof UsersUserIdRoute
  UsersNewRoute: typeof UsersNewRoute
  FilesIndexRoute: typeof FilesIndexRoute
  StorageIndexRoute: typeof StorageIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitations': {
      id: '/invitations'
      path: '/invitations'
      fullPath: '/invitations'
      preLoaderRoute: typeof InvitationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/username-requests': {
      id: '/username-requests'
      path: '/username-requests'
      fullPath: '/username-requests'
      preLoaderRoute: typeof UsernameRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files/': {
      id: '/files/'
      path: '/files'
      fullPath: '/files/'
      preLoaderRoute: typeof FilesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/sharing': {
      id: '/settings/sharing'
      path: '/settings/sharing'
      fullPath: '/settings/sharing'
      preLoaderRoute: typeof SettingsSharingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storage/': {
      id: '/storage/'
      path: '/storage'
      fullPath: '/storage/'
      preLoaderRoute: typeof StorageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$userId': {
      id: '/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/new': {
      id: '/users/new'
      path: '/users/new'
      fullPath: '/users/new'
      preLoaderRoute: typeof UsersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InvitationsRoute: InvitationsRoute,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
  UsernameRequestsRoute: UsernameRequestsRoute,
  SettingsSharingRoute: SettingsSharingRoute,
  UsersUserIdRoute: UsersUserIdRoute,
  UsersNewRoute: UsersNewRoute,
  FilesIndexRoute: FilesIndexRoute,
  StorageIndexRoute: StorageIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
