/**
 * `@ekoz/sdk` public surface.
 */

export { createClient, type EkozClient, type SessionController } from './client.js';
export type { ClientConfig } from './config.js';
export {
  Discovery,
  type DiscoveryDocument,
  type DiscoveryOptions,
  SUPPORTED_PROTOCOL_MAJORS,
  WELL_KNOWN_PATH,
} from './discovery/discovery.js';
export type { DirectoryResource, ListDirectoryParams } from './resources/directory.js';
export type {
  ListMessagesParams,
  MessagesResource,
  SendMessageBody,
} from './resources/messages.js';
export type { RoomInvitationsResource } from './resources/room-invitations.js';
export type {
  ListJoinRequestsParams,
  ListMembersParams,
  RoomsResource,
} from './resources/rooms.js';
export type {
  AccountStreamEvent,
  EventSourceConstructor,
  EventSourceLike,
  EventSourceMessageLike,
  PresenceStreamEvent,
  RoomStream,
  RoomStreamEventMap,
  RoomStreamEventName,
  RoomStreamRoomEvent,
  RoomStreamStatus,
  TypingStreamEvent,
} from './resources/stream.js';
export type { SyncParams, SyncResource } from './resources/sync.js';
export type {
  SessionEventMap,
  SessionEventName,
  SessionInvalidReason,
} from './session/events.js';
export type { AuthBundle } from './session/session-manager.js';
export type { SessionState, SessionStore } from './session/session-store.js';
export { memoryStore } from './session/session-store.js';
export {
  AccountSuspendedError,
  AuthenticationError,
  EkozError,
  type EkozErrorInit,
  EmailNotVerifiedError,
  EmailTakenError,
  InvalidCredentialsError,
  InvitationInvalidError,
  LastOwnerError,
  NetworkError,
  NotFoundError,
  type ProblemDetails,
  ProtocolMismatchError,
  RateLimitError,
  RefreshInvalidError,
  RefreshReuseError,
  RegistrationClosedError,
  ServerError,
  UsernameChangeCooldownError,
  UsernameImmutableError,
  UsernameTakenError,
  ValidationError,
  type ValidationIssue,
  WeakPasswordError,
} from './transport/errors.js';
export {
  DEFAULT_PROTOCOL_VERSION,
  HttpClient,
  type HttpClientOptions,
  type HttpMethod,
  PROTOCOL_HEADER,
  type QueryValue,
  type RequestOptions,
} from './transport/http-client.js';
export {
  decodeProblem,
  ERROR_CODE_MAP,
  parseRetryAfter,
  toNetworkError,
} from './transport/problem.js';
export {
  newRequestId,
  REQUEST_ID_HEADER,
  resolveRequestId,
} from './transport/request-context.js';
export type {
  MessageCreatedEvent,
  MessageDeletedEvent,
  MessageEditedEvent,
  MessageRedactedEvent,
  OtherRoomEventType,
  RoomEvent,
  RoomEventBase,
  SyncResponse,
  UnknownRoomEvent,
} from './types/events.js';
export {
  AcceptedResponseSchema,
  AccountViewSchema,
  AddOwnerBodySchema,
  AdminCreateUserBodySchema,
  AdminUserDetailSchema,
  AdminUserListItemSchema,
  AdminUserListResponseSchema,
  AuthPolicySchema,
  AvatarUploadedSchema,
  ChangeEmailBodySchema,
  ChangePasswordBodySchema,
  ChangeUsernameBodySchema,
  ConfirmPasswordResetBodySchema,
  CreateChannelBodySchema,
  CreatedInvitationSchema,
  CreateInvitationBodySchema,
  CreateSpaceBodySchema,
  DeleteMeBodySchema,
  DirectoryListResponseSchema,
  EmailAcceptedResponseSchema,
  EmailVerifiedResponseSchema,
  InvitationsListResponseSchema,
  InvitationViewSchema,
  JoinRequestSchema,
  LoginBodySchema,
  LoginResponseSchema,
  MemberSchema,
  MembershipSchema,
  MembersPageSchema,
  MessageSchema,
  MessagesPageSchema,
  MeViewSchema,
  MyPermissionsResponseSchema,
  MyRoomInvitationSchema,
  MyRoomInvitationsListResponseSchema,
  PendingJoinRequestSchema,
  PendingJoinRequestsPageSchema,
  PublicProfileViewSchema,
  RegisterBodySchema,
  RenameSessionBodySchema,
  RequestPasswordResetBodySchema,
  ResendVerificationBodySchema,
  RevokeAllSessionsResponseSchema,
  RoomListItemSchema,
  RoomListResponseSchema,
  RoomPreviewSchema,
  RoomSchema,
  SessionsListResponseSchema,
  SessionViewSchema,
  SetupOwnerBodySchema,
  SetupOwnerResponseSchema,
  SetupStateResponseSchema,
  StreamTicketSchema,
  SuspendUserBodySchema,
  TokenBundleSchema,
  UpdateProfileBodySchema,
  UsernameApprovedSchema,
  UsernameChangeAppliedSchema,
  UsernameChangeOutcomeSchema,
  UsernameChangePendingRequestSchema,
  UsernameChangePendingSchema,
  UsernameChangeRequestSchema,
  UsernameChangeStateSchema,
  UsernameRequestsListResponseSchema,
  UserSummaryListSchema,
  UserSummarySchema,
  VerifyEmailBodySchema,
} from './types/schemas.js';
export type {
  AcceptedResponse,
  AccountView,
  AddOwnerBody,
  AdminCreateUserBody,
  AdminUserDetail,
  AdminUserListItem,
  AdminUserListResponse,
  AuthPolicy,
  AvatarUploaded,
  ChangeEmailBody,
  ChangePasswordBody,
  ChangeUsernameBody,
  ConfirmPasswordResetBody,
  CreateChannelBody,
  CreatedInvitation,
  CreateInvitationBody,
  CreateSpaceBody,
  DeleteMeBody,
  DirectoryListResponse,
  EmailAcceptedResponse,
  EmailVerifiedResponse,
  InvitationsListResponse,
  InvitationView,
  JoinRequest,
  LoginBody,
  LoginResponse,
  Member,
  Membership,
  MembersPage,
  Message,
  MessagesPage,
  MeView,
  MyPermissionsResponse,
  MyRoomInvitation,
  MyRoomInvitationsListResponse,
  PendingJoinRequest,
  PendingJoinRequestsPage,
  PublicProfileView,
  RegisterBody,
  RenameSessionBody,
  RequestPasswordResetBody,
  ResendVerificationBody,
  RevokeAllSessionsResponse,
  Room,
  RoomListItem,
  RoomListResponse,
  RoomPreview,
  SessionsListResponse,
  SessionView,
  SetupOwnerBody,
  SetupOwnerResponse,
  SetupStateResponse,
  StreamTicket,
  SuspendUserBody,
  TokenBundle,
  UpdateProfileBody,
  UsernameApproved,
  UsernameChangeApplied,
  UsernameChangeOutcome,
  UsernameChangePending,
  UsernameChangePendingRequest,
  UsernameChangeRequest,
  UsernameChangeState,
  UsernameRequestsListResponse,
  UserSummary,
  UserSummaryList,
  VerifyEmailBody,
} from './types/wire.js';
