import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// Generated by docusaurus-plugin-typedoc (see docusaurus.config.ts) before sidebars are loaded.
const typedocSidebar = require('./sdk/api/typedoc-sidebar.cjs');

const sidebars: SidebarsConfig = {
  sdk: [
    {
      type: 'category',
      label: 'Guide',
      items: ['guide/intro', 'guide/quickstart', 'guide/auth', 'guide/realtime'],
    },
    {
      type: 'category',
      label: 'API reference',
      link: { type: 'doc', id: 'api/index' },
      items: typedocSidebar,
    },
  ],
};

export default sidebars;
