/**
 * Zod validation schemas for the wire (payload) types in `./wire.ts`, sourced
 * from `../generated/api/zod-api` (technical.md §11.2).
 *
 * `zodGenerator` emits the same ten Prisma-style variants per schema as
 * `typescriptGenerator` does for `wire.ts`, but only a single `Dto` suffix on
 * each const (`LoginResponseDtoSchema`, not `LoginResponseDtoDtoSchema`) since
 * the generated type name — not the schema const — is what carries the
 * duplicate suffix. This module re-exports only the flat variant, one schema
 * per `wire.ts` export, named `<WireTypeName>Schema` so `zodResolver` call
 * sites pair a form's type with its schema by name
 * (`useForm<AdminCreateUserBody>({ resolver: zodResolver(AdminCreateUserBodySchema) })`).
 * No field is redeclared — a mismatch with the server is a generated-contract
 * bug, fixed by regenerating, never patched here.
 */

export {
  AcceptedResponseDtoSchema as AcceptedResponseSchema,
  AccountViewDtoSchema as AccountViewSchema,
  AddOwnerDtoSchema as AddOwnerBodySchema,
  AdminCreateUserDtoSchema as AdminCreateUserBodySchema,
  AdminUserDetailDtoSchema as AdminUserDetailSchema,
  AdminUserListResponseDtoItemsSchema as AdminUserListItemSchema,
  AdminUserListResponseDtoSchema as AdminUserListResponseSchema,
  AdminUsernameRequestsController_list200ResponseJsonSchema as UsernameRequestsListResponseSchema,
  AuthPolicyDtoSchema as AuthPolicySchema,
  AvatarUploadedDtoSchema as AvatarUploadedSchema,
  ChangeEmailDtoSchema as ChangeEmailBodySchema,
  ChangePasswordDtoSchema as ChangePasswordBodySchema,
  ChangeUsernameDtoSchema as ChangeUsernameBodySchema,
  ConfirmPasswordResetDtoSchema as ConfirmPasswordResetBodySchema,
  CreateChannelDtoSchema as CreateChannelBodySchema,
  CreatedInvitationDtoSchema as CreatedInvitationSchema,
  CreateInvitationDtoSchema as CreateInvitationBodySchema,
  CreateSpaceDtoSchema as CreateSpaceBodySchema,
  DeleteMeDtoSchema as DeleteMeBodySchema,
  DirectoryListResponseDtoSchema as DirectoryListResponseSchema,
  EmailAcceptedResponseDtoSchema as EmailAcceptedResponseSchema,
  EmailVerifiedResponseDtoSchema as EmailVerifiedResponseSchema,
  GroupDetailDtoSchema as GroupDetailSchema,
  GroupListViewDtoItemsSchema as GroupSchema,
  GroupListViewDtoSchema as GroupListResponseSchema,
  InvitationsController_list200ResponseJsonSchema as InvitationsListResponseSchema,
  InvitationViewDtoSchema as InvitationViewSchema,
  JoinRequestViewDtoSchema as JoinRequestSchema,
  LoginDtoSchema as LoginBodySchema,
  LoginResponseDtoSchema as LoginResponseSchema,
  MemberListViewDtoItemsSchema as MemberSchema,
  MemberListViewDtoSchema as MembersPageSchema,
  MembershipViewDtoSchema as MembershipSchema,
  MessagePageDtoSchema as MessagesPageSchema,
  MessagePinViewDtoSchema as MessagePinSchema,
  MessagesPolicyDtoSchema as MessagesPolicySchema,
  MessageViewDtoMentionsSchema as MentionTargetSchema,
  MessageViewDtoReactionsSchema as MessageReactionSchema,
  MessageViewDtoSchema as MessageSchema,
  MeUsernameController_change200ResponseJsonSchema as UsernameChangeOutcomeSchema,
  MeViewDtoSchema as MeViewSchema,
  MyMentionsPageDtoItemsSchema as MyMentionSchema,
  MyMentionsPageDtoSchema as MyMentionsPageSchema,
  MyPermissionsResponseDtoSchema as MyPermissionsResponseSchema,
  MyRoomInvitationListViewDtoItemsSchema as MyRoomInvitationSchema,
  MyRoomInvitationListViewDtoSchema as MyRoomInvitationsListResponseSchema,
  PendingJoinRequestListViewDtoItemsSchema as PendingJoinRequestSchema,
  PendingJoinRequestListViewDtoItemsUserSchema as UserSummarySchema,
  PendingJoinRequestListViewDtoSchema as PendingJoinRequestsPageSchema,
  PublicProfileViewDtoSchema as PublicProfileViewSchema,
  RegisterDtoSchema as RegisterBodySchema,
  RenameSessionDtoSchema as RenameSessionBodySchema,
  RequestPasswordResetDtoSchema as RequestPasswordResetBodySchema,
  ResendVerificationDtoSchema as ResendVerificationBodySchema,
  RevokeAllSessionsResponseDtoSchema as RevokeAllSessionsResponseSchema,
  RoomListViewDtoItemsSchema as RoomListItemSchema,
  RoomListViewDtoSchema as RoomListResponseSchema,
  RoomPreviewDtoSchema as RoomPreviewSchema,
  RoomViewDtoSchema as RoomSchema,
  SessionsController_list200ResponseJsonSchema as SessionsListResponseSchema,
  SessionViewDtoSchema as SessionViewSchema,
  SetupOwnerDtoSchema as SetupOwnerBodySchema,
  SetupOwnerResponseDtoSchema as SetupOwnerResponseSchema,
  SetupStateDtoSchema as SetupStateResponseSchema,
  StreamTicketResponseDtoSchema as StreamTicketSchema,
  SuspendUserDtoSchema as SuspendUserBodySchema,
  TokenBundleDtoSchema as TokenBundleSchema,
  UnreadMentionsViewDtoItemsSchema as UnreadMentionsSchema,
  UnreadMentionsViewDtoSchema as UnreadMentionsResponseSchema,
  UpdateProfileDtoSchema as UpdateProfileBodySchema,
  UsernameApprovedDtoSchema as UsernameApprovedSchema,
  UsernameChangeAppliedDtoSchema as UsernameChangeAppliedSchema,
  UsernameChangePendingDtoSchema as UsernameChangePendingSchema,
  UsernameChangeRequestDtoSchema as UsernameChangeRequestSchema,
  UsernameChangeStateDtoPendingRequestSchema as UsernameChangePendingRequestSchema,
  UsernameChangeStateDtoSchema as UsernameChangeStateSchema,
  UserSummaryListViewDtoSchema as UserSummaryListSchema,
  VerifyEmailDtoSchema as VerifyEmailBodySchema,
} from '../generated/api/zod-api/index.js';
