/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAccountRouteImport } from './routes/_app/account'
import { Route as AppRoomsRouteImport } from './routes/_app/rooms'
import { Route as AuthCheckEmailRouteImport } from './routes/_auth/check-email'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthVerifyEmailRouteImport } from './routes/_auth/verify-email'
import { Route as AppRoomsIndexRouteImport } from './routes/_app/rooms/index'
import { Route as AppRoomsRoomIdRouteImport } from './routes/_app/rooms/$roomId'
import { Route as AppRoomsDirectoryRouteImport } from './routes/_app/rooms/directory'
import { Route as AppRoomsInvitationsRouteImport } from './routes/_app/rooms/invitations'
import { Route as AppRoomsNewRouteImport } from './routes/_app/rooms/new'
import { Route as AppRoomsRoomIdRequestsRouteImport } from './routes/_app/rooms/$roomId/requests'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppRoomsRoute = AppRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AppRoute,
} as any)
const AuthCheckEmailRoute = AuthCheckEmailRouteImport.update({
  id: '/check-email',
  path: '/check-email',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRoute,
} as any)
const AppRoomsIndexRoute = AppRoomsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoomsRoute,
} as any)
const AppRoomsRoomIdRoute = AppRoomsRoomIdRouteImport.update({
  id: '/$roomId',
  path: '/$roomId',
  getParentRoute: () => AppRoomsRoute,
} as any)
const AppRoomsDirectoryRoute = AppRoomsDirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => AppRoomsRoute,
} as any)
const AppRoomsInvitationsRoute = AppRoomsInvitationsRouteImport.update({
  id: '/invitations',
  path: '/invitations',
  getParentRoute: () => AppRoomsRoute,
} as any)
const AppRoomsNewRoute = AppRoomsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppRoomsRoute,
} as any)
const AppRoomsRoomIdRequestsRoute = AppRoomsRoomIdRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AppRoomsRoomIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/account': typeof AppAccountRoute
  '/rooms': typeof AppRoomsRouteWithChildren
  '/check-email': typeof AuthCheckEmailRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/rooms/$roomId': typeof AppRoomsRoomIdRouteWithChildren
  '/rooms/directory': typeof AppRoomsDirectoryRoute
  '/rooms/invitations': typeof AppRoomsInvitationsRoute
  '/rooms/new': typeof AppRoomsNewRoute
  '/rooms/': typeof AppRoomsIndexRoute
  '/rooms/$roomId/requests': typeof AppRoomsRoomIdRequestsRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/account': typeof AppAccountRoute
  '/check-email': typeof AuthCheckEmailRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/rooms/$roomId': typeof AppRoomsRoomIdRouteWithChildren
  '/rooms/directory': typeof AppRoomsDirectoryRoute
  '/rooms/invitations': typeof AppRoomsInvitationsRoute
  '/rooms/new': typeof AppRoomsNewRoute
  '/rooms': typeof AppRoomsIndexRoute
  '/rooms/$roomId/requests': typeof AppRoomsRoomIdRequestsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/account': typeof AppAccountRoute
  '/_app/rooms': typeof AppRoomsRouteWithChildren
  '/_auth/check-email': typeof AuthCheckEmailRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/verify-email': typeof AuthVerifyEmailRoute
  '/_app/': typeof AppIndexRoute
  '/_app/rooms/$roomId': typeof AppRoomsRoomIdRouteWithChildren
  '/_app/rooms/directory': typeof AppRoomsDirectoryRoute
  '/_app/rooms/invitations': typeof AppRoomsInvitationsRoute
  '/_app/rooms/new': typeof AppRoomsNewRoute
  '/_app/rooms/': typeof AppRoomsIndexRoute
  '/_app/rooms/$roomId/requests': typeof AppRoomsRoomIdRequestsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/rooms'
    | '/check-email'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/rooms/$roomId'
    | '/rooms/directory'
    | '/rooms/invitations'
    | '/rooms/new'
    | '/rooms/'
    | '/rooms/$roomId/requests'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/check-email'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/rooms/$roomId'
    | '/rooms/directory'
    | '/rooms/invitations'
    | '/rooms/new'
    | '/rooms'
    | '/rooms/$roomId/requests'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_app/account'
    | '/_app/rooms'
    | '/_auth/check-email'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/reset-password'
    | '/_auth/verify-email'
    | '/_app/'
    | '/_app/rooms/$roomId'
    | '/_app/rooms/directory'
    | '/_app/rooms/invitations'
    | '/_app/rooms/new'
    | '/_app/rooms/'
    | '/_app/rooms/$roomId/requests'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rooms': {
      id: '/_app/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof AppRoomsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/check-email': {
      id: '/_auth/check-email'
      path: '/check-email'
      fullPath: '/check-email'
      preLoaderRoute: typeof AuthCheckEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/verify-email': {
      id: '/_auth/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/rooms/': {
      id: '/_app/rooms/'
      path: '/'
      fullPath: '/rooms/'
      preLoaderRoute: typeof AppRoomsIndexRouteImport
      parentRoute: typeof AppRoomsRoute
    }
    '/_app/rooms/$roomId': {
      id: '/_app/rooms/$roomId'
      path: '/$roomId'
      fullPath: '/rooms/$roomId'
      preLoaderRoute: typeof AppRoomsRoomIdRouteImport
      parentRoute: typeof AppRoomsRoute
    }
    '/_app/rooms/directory': {
      id: '/_app/rooms/directory'
      path: '/directory'
      fullPath: '/rooms/directory'
      preLoaderRoute: typeof AppRoomsDirectoryRouteImport
      parentRoute: typeof AppRoomsRoute
    }
    '/_app/rooms/invitations': {
      id: '/_app/rooms/invitations'
      path: '/invitations'
      fullPath: '/rooms/invitations'
      preLoaderRoute: typeof AppRoomsInvitationsRouteImport
      parentRoute: typeof AppRoomsRoute
    }
    '/_app/rooms/new': {
      id: '/_app/rooms/new'
      path: '/new'
      fullPath: '/rooms/new'
      preLoaderRoute: typeof AppRoomsNewRouteImport
      parentRoute: typeof AppRoomsRoute
    }
    '/_app/rooms/$roomId/requests': {
      id: '/_app/rooms/$roomId/requests'
      path: '/requests'
      fullPath: '/rooms/$roomId/requests'
      preLoaderRoute: typeof AppRoomsRoomIdRequestsRouteImport
      parentRoute: typeof AppRoomsRoomIdRoute
    }
  }
}

interface AppRoomsRoomIdRouteChildren {
  AppRoomsRoomIdRequestsRoute: typeof AppRoomsRoomIdRequestsRoute
}

const AppRoomsRoomIdRouteChildren: AppRoomsRoomIdRouteChildren = {
  AppRoomsRoomIdRequestsRoute: AppRoomsRoomIdRequestsRoute,
}

const AppRoomsRoomIdRouteWithChildren = AppRoomsRoomIdRoute._addFileChildren(
  AppRoomsRoomIdRouteChildren,
)

interface AppRoomsRouteChildren {
  AppRoomsRoomIdRoute: typeof AppRoomsRoomIdRouteWithChildren
  AppRoomsDirectoryRoute: typeof AppRoomsDirectoryRoute
  AppRoomsInvitationsRoute: typeof AppRoomsInvitationsRoute
  AppRoomsNewRoute: typeof AppRoomsNewRoute
  AppRoomsIndexRoute: typeof AppRoomsIndexRoute
}

const AppRoomsRouteChildren: AppRoomsRouteChildren = {
  AppRoomsRoomIdRoute: AppRoomsRoomIdRouteWithChildren,
  AppRoomsDirectoryRoute: AppRoomsDirectoryRoute,
  AppRoomsInvitationsRoute: AppRoomsInvitationsRoute,
  AppRoomsNewRoute: AppRoomsNewRoute,
  AppRoomsIndexRoute: AppRoomsIndexRoute,
}

const AppRoomsRouteWithChildren = AppRoomsRoute._addFileChildren(
  AppRoomsRouteChildren,
)

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppRoomsRoute: typeof AppRoomsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppRoomsRoute: AppRoomsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthCheckEmailRoute: typeof AuthCheckEmailRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCheckEmailRoute: AuthCheckEmailRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
